repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-cyclo
<<<<<<< HEAD
        args: [ -over=15 ]
=======
        args: [ -over=15 ]
>>>>>>> 9754732 (feat: Update to V2)
